name: CI e Versionamento

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  ci:
    name: Testes (HTML, CSS, JS, PHP)
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Criar pasta de relatórios
        run: mkdir -p relatorios

      - name: Lint HTMLHint
        run: htmlhint '*.html' > relatorios/htmlhint.txt || true

      - name: Lint ESLint (HTML)
        run: eslint '*.html' -f unix > relatorios/eslint-html.txt || true

      - name: Lint ESLint (JS)
        run: eslint 'src/js/**/*.js' -f unix > relatorios/eslint-js.txt || true

      - name: Lint Stylelint
        run: stylelint 'css/**/*.css' > relatorios/stylelint.txt || true

      - name: Lint PHP
        run: node scripts/php-lint.js > relatorios/php-lint.txt || true

      - name: Upload dos relatórios
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-lint
          path: relatorios

  release:scripts
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Instalar dependências
        run: npm install

      - name: Rodar semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
